### ISSUE TITLE
bin/pimple-etl config.sample.php fails

### ISSUE THREAD

**Issue by umpirsky** [docteurklein/php-etl#26]
It is in readme, and it fails:

```
$ bin/pimple-etl config.sample.php
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'SplFileObject::__construct(csv/users.csv): failed to open stream: No such file or directory' in src/Knp/ETL/Extractor/CsvExtractor.php:29
Stack trace:
#0 src/Knp/ETL/Extractor/CsvExtractor.php(29): SplFileObject->__construct('/home/umpirsky/...')
#1 config.sample.php(36): Knp\ETL\Extractor\CsvExtractor->__construct('/home/umpirsky/...', ';', '"', 0)
#2 vendor/pimple/pimple/src/Pimple/Container.php(113): {closure}(Object(Pimple\Container))
#3 bin/pimple-etl(17): Pimple\Container->offsetGet('e')
#4 {main}
  thrown in src/Knp/ETL/Extractor/CsvExtractor.php on line 29

Fatal error: Uncaught exception 'RuntimeException' with message 'SplFileObject::__construct(csv/users.csv): failed to open stream: No such file or directory' in src/Knp/ETL/Extractor/CsvExtractor.php on line 29

RuntimeException: SplFileObject::__construct(csv/users.csv): failed to open stream: No such file or directory in src/Knp/ETL/Extractor/CsvExtractor.php on line 29

Call Stack:
    0.0030     638128   1. {main}() bin/pimple-etl:0
    0.0047     971928   2. Pimple\Container->offsetGet() bin/pimple-etl:17
    0.0047     971960   3. {closure:config.sample.php:36-36}() vendor/pimple/pimple/src/Pimple/Container.php:113
    0.0050    1002152   4. Knp\ETL\Extractor\CsvExtractor->__construct() config.sample.php:36
    0.0050    1006568   5. SplFileObject->__construct() src/Knp/ETL/Extractor/CsvExtractor.php:29
```

Not very user friendly.

I suggest adding user entity and csv to fixtures and make it work by default.

Or providing some more basic example like suggested in https://github.com/docteurklein/php-etl/issues/24#issuecomment-172363131.

**Comment by jasonhai** [comment]
Hello Umpirsky,

I'm following your instruction in this project to test ETL, but unfortunately, the process is not working anymore.

When I run this command:  bin/pimple-etl config.sample.php

It was displayed : No such file or directory.

Could you please to checked it and give me your update?

Thanks and regards!
         Jason

**Comment by umpirsky** [comment]
@jasonhai Can you paste entire console output including how you run the script?
